# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: debug-statements
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bandit
        -   flake8-broken-line
        -   flake8-bugbear
        -   flake8-builtins
        -   flake8-debugger
        -   flake8-docstrings
        -   flake8-eradicate
        -   flake8-flask
        -   flake8-implicit-str-concat
        -   flake8-import-order
        -   flake8-pytest
        -   flake8-pytest-style
        -   flake8-quotes
        -   pep8-naming
        -   mccabe
-   repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
    -   id: codespell
        entry: codespell --ignore-words ignore-spelling-words.txt *.py *.md
